name: C/C++ CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.7.0
    steps:
    - uses: actions/checkout@v4
    - name: install pybind11
      run: pip3 install pybind11[global]
    - name: build
      run: cd src && pip3 install .
    - name: test
      run: cd test && python3 -m pytest -s -v .
