name: C/C++ CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: dolfinx/dolfinx:v0.7.2
    steps:
    - uses: actions/checkout@v4
    - name: Python lint
      run: |
        pip3 install ruff
        ruff check --preview .
    - name: build
      run: pip3 install .
    - name: test serial
      run: |
        cd test
        python3 -m pytest -s -v .
    - name: test parallel
      run: |
        cd test
        mpirun -np 2 python3 -m pytest -s -v .
